CREATE DATABASE agencia_viajes;
-- Conéctese a agencia_viajes antes de continuar.

CREATE TABLE destinos (
    destino_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pais VARCHAR(80) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    descripcion VARCHAR(300) NOT NULL,
    temporada VARCHAR(80) NOT NULL
);

CREATE TABLE paquetes (
    paquete_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destino_id INTEGER NOT NULL REFERENCES destinos(destino_id) ON DELETE RESTRICT,
    nombre VARCHAR(150) NOT NULL,
    precio NUMERIC(12,2) NOT NULL CHECK (precio > 0),
    duracion INTEGER NOT NULL CHECK (duracion BETWEEN 1 AND 365)
);

CREATE TABLE clientes (
    cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    documento VARCHAR(30) NOT NULL UNIQUE,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE reservas (
    reserva_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL REFERENCES clientes(cliente_id) ON DELETE RESTRICT,
    paquete_id INTEGER NOT NULL REFERENCES paquetes(paquete_id) ON DELETE RESTRICT,
    fecha_reserva TIMESTAMPTZ NOT NULL,
    estado VARCHAR(30) NOT NULL CHECK (estado IN ('Pendiente','Confirmada','Cancelada','Completada'))
);

INSERT INTO destinos(pais, ciudad, descripcion, temporada) VALUES
('Ecuador','Galápagos','Recorrido por islas, fauna y playas volcánicas.','Todo el año'),
('Perú','Cusco','Visita cultural a Cusco y Machu Picchu.','Mayo a septiembre'),
('Colombia','Cartagena','Experiencia histórica y playas del Caribe.','Diciembre a abril');

INSERT INTO paquetes(destino_id,nombre,precio,duracion) VALUES
(1,'Galápagos Natural',1250.00,5),
(2,'Cusco y Machu Picchu',890.00,4),
(3,'Cartagena Caribe',720.00,4);

INSERT INTO clientes(nombre,documento,telefono,email) VALUES
('Ana Torres','1712345678','0991234567','ana.torres@example.com'),
('Carlos Mena','1723456789','0982345678','carlos.mena@example.com'),
('María Paredes','1734567890','0973456789','maria.paredes@example.com');

INSERT INTO reservas(cliente_id,paquete_id,fecha_reserva,estado)
VALUES (1,1,NOW() + INTERVAL '15 day','Confirmada');
